version: "3.1"
services:
    db:
        ports:
            - 5432:5432

    graphql:
        environment:
            - ALLOW_EXPLAIN=true
        ports:
            - 5433:5433

    app:
        volumes:
            - ./app/init/public:/srv/app/public
            - ./app/init/src:/srv/app/src
        command: ["dev"]

    nginx:
        ports:
            - 8080:8080

    scripts:
        volumes:
            - ./scripts/init:/srv/scripts
        tty: true
